/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ECL.h
 #	source generated by 4D Plugin Wizard
 #	Project : ECL
 #	author : miyako
 #	2021/11/16
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ECL_H
#define PLUGIN_ECL_H

#include "4DPluginAPI.h"

#include <ecl/ecl.h>
#include <stdlib.h>
#include <stdio.h>

#pragma mark -

void lisp(PA_PluginParameters params);

#include "4DPlugin-JSON.h"

static void u16_to_u8(CUTF16String& u16, std::string& u8);
static void u8_to_u16(std::string& u8, CUTF16String& u16);

typedef std::basic_string<ecl_character> CUTF32String;

#if VERSIONMAC
#define CPathString CUTF8String
#define CPathOpen fopen
#define CPathAppend "ab"
#define CPathCreate "wb"
#define CPathRead "rb"
#else
#include <Shlobj.h>
#define CPathString CUTF16String
#define CPathOpen _wfopen
#define CPathAppend L"ab"
#define CPathCreate L"wb"
#define CPathRead L"rb"
#endif

#endif /* PLUGIN_ECL_H */
